DELETE FROM video;
INSERT INTO video VALUES (NULL,'A Christmas Story','comedy','Peter Billingsley, Melinda Dillon','Bob Clark','PG','1983-11-18','94');
INSERT INTO video VALUES (NULL,'Dear John','romance','Channing Tatum, Amanda Seyfried','Lasse Hallström','PG-13','2010-02-05','108');
INSERT INTO video VALUES (NULL,'Despicable Me','animated','Steve Carell, Jason Segel','Pierre Coffin, Chris Renaud','PG','2010-07-09','95');
INSERT INTO video VALUES (NULL,'Dumb & Dumber','comedy','Jim Carrey, Jeff Daniels','Peter Farrelly, Bobby Farrelly','PG-13','1994-12-16','107');
INSERT INTO video VALUES (NULL,'Elf','comedy','Will Ferrell, James Caan','Jon Favreau','PG','2003-11-07','97');
INSERT INTO video VALUES (NULL,'Finding Nemo','animated','Albert Brooks, Ellen DeGeneres','Andrew Stanton, Lee Unkrich','G','2003-05-30','100');
INSERT INTO video VALUES (NULL,'Forrest Gumps','drama','Tom Hanks, Robin Wright','Robert Zemeckis','PG-13','1994-07-06','142');
INSERT INTO video VALUES (NULL,'Gladiator','action','Russell Crowe, Joaquin Phoenix','Ridley Scott','R','2000-05-05','155');
INSERT INTO video VALUES (NULL,'Gran Torino','drama','Clint Eastwood, Bee Vang','Clint Eastwood','R','2009-01-09','116');
INSERT INTO video VALUES (NULL,'Knocked Up','comedy','Seth Rogen, Katherine Heigl','Judd Apatow','R','2007-06-01','129');
INSERT INTO video VALUES (NULL,'50 First Dates','comedy','Adam Sandler, Drew Barrymore, Rob Schneider','Peter Segal','PG-13','2004-02-13','99');
INSERT INTO video VALUES (NULL,'Independence Day','action, adventure, sci-fi','Will Smith, Bill Pullman, Jeff Goldblum','Roland Emmerich','PG-13','1996-07-03','145');
INSERT INTO video VALUES (NULL,'War of the Worlds','adventure, sci-fi, thriller','Tom Cruise, Dakota Fanning, Tim Robbinsvideo','Steven Spielberg','PG-13','2005-06-29','116');
INSERT INTO video VALUES (NULL,'Meet the Fockers','comedy, romance','Ben Stiller, Robert De Niro, Blythe Danner','Jay Roach','PG-13','2004-12-22','115');
INSERT INTO video VALUES (NULL,'The Day After Tomorrow','action, adventure, sci-fi','Dennis Quaid, Jake Gyllenhaal, Emmy Rossum','Roland Emmerich','PG-13','2004-05-28','124');
INSERT INTO video VALUES (NULL,'2012','action, adventure, sci-fi','John Cusack, Thandie Newton, Chiwetel Ejiofor','Roland Emmerich','PG-13','2009-11-13','158');
INSERT INTO video VALUES (NULL,'Bridget Jones’s Diary','comedy, romance','Renée Zellweger, Colin Firth, Hugh Grant','Sharon Maguire','R','2001-04-13','97');
INSERT INTO video VALUES (NULL,'Terminator 2','action, sci-fi','Arnold Schwarzenegger, Linda Hamilton','James Cameron','R','1991-07-03','137');
INSERT INTO video VALUES (NULL,'Titanic','drama, romance','Leonardo DiCaprio, Kate Winslet','James Cameron','PG-13','1997-12-19','194');
INSERT INTO video VALUES (NULL,'Saving Private Ryan','action, drama, war','Tom Hanks, Matt Damon, Tom Sizemore','Steven Spielberg','R','1998-07-24','169');
INSERT INTO video VALUES (NULL,'Schindler’s List','drama, history','Liam Neeson, Ralph Fiennes','Steven Spielberg','R','1994-02-04','195');